### PR TITLE
register and login screen updated

### PR DESCRIPTION
**Pull request by varchodi**
#26 
hey guys I updated the login and register page, and integrate react-router and tailwind CSS

### CODE REVIEW

**Comment by varchodi** [comment]
there is a height problem on login screen , i have fixed it ,

**Comment by varchodi** [comment]
image
login screen 
image
as register screen

**Comment by AliMora83** [comment]
Looking good @varchodi 🥳

**Review by AliMora83 — COMMENTED** [review]
Thank you 🥳

**Pull request merged**
